version: '3'
services:
  php:
    build: .
    container_name: banner_click
    volumes:
      - .:/var/www
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379